### ISSUE TITLE
203. 使用栅格化做响应式的时候，如何优雅的控制间距？定义多个快捷键吗？

### ISSUE THREAD

**Issue by ly525** [ly525/blog#203]
1. 比如 在PC 版本的时候，chart 靠左边对齐，但是在移动版的时候，就不适合了，因为靠左边的就会导致数字被覆盖，如下图所示。
> ![image](https://user-images.githubusercontent.com/12668546/48065549-023c7d80-e206-11e8-8fe0-fa0503ac267e.png)
> 现在的解决方案是：定一个 class，移除间距
```css
@media screen and (max-width: 960px) {
  .sm-screen-margin-y {
    margin-top: 10px;
  }

  .sm-screen-margin-x-0 {
    margin-left: 0;
    margin-right: 0;
  }
}
```
