### ISSUE TITLE
250. 日期选择器(DateRangePicker) 的  CSS 设计思路

### ISSUE THREAD

**Issue by ly525** [ly525/blog#250]
1. Why style scoped and what style scoped does?
2. Do I need style scoped for the date-range-picker? the advantages and disadvantages of it?

### box-sizing
1. use `box-sizing：border-box;` for input box
> without `box-sizing: border-box;`
> because the the icon is inside the input box with padding-left, so the input box is pushed to the right.

> ![box-sizing](http://jietu-10024907.file.myqcloud.com/wgmvzpfmebjmmwlcpshlqhyndpemeiza.jpg)
> ![](http://jietu-10024907.file.myqcloud.com/iyvyrrzixqywztdfmznlinqxvspgscpm.jpg)

> [Solved] add `box-sizing: border-box` for input box
> ![](http://jietu-10024907.file.myqcloud.com/ivmejgvcxobommycdqxvkjtlcoafjyab.jpg)

### day.off
1. Items that do not belong to the current month（ 不属于当前月份的 item）
```scss
td,
th {
  &.off,
  &.off.in-range,
  &.off.start-date,
  &.off.end-date {
    background-color: #fff;
    border-color: transparent;
    color: #999;
  }
}
```
> ![](http://jietu-10024907.file.myqcloud.com/eytzbtngenkqzraihjnbjhiubefeohql.jpg)
> without `.off` style:
> ![](http://jietu-10024907.file.myqcloud.com/alvlbbhaaugfrlotdrjoxfvjlrdvosmf.jpg)
