### ISSUE TITLE
347: ams 学习

### ISSUE THREAD

**Issue by ly525** [ly525/blog#348]
TODO

**Comment by ly525** [comment]
## 表格适配 TODO
1. 以 list 的 actions 列为例，最后的按钮默认配置size: 'mini' 会比较合适，这样表格在数据量比较多的情况下。不会被撑的很高。表格每一行的高度在添加actions 前后最好保持一致！
```
'type': 'button',
'label': '投放数据',
'props': {
  'type': 'text',
  size: 'mini',
},
```

但发现最后的 actions 被放到了el-form 里面，发现要重写下面的样式，将 el-form-item 的margin-bottom  设置为0 比较合适

```css
.ams-block .ams-operations .el-form-item {
    margin-bottom: 0;
}
```
