### ISSUE TITLE
61. 组件设计-Button

### ISSUE THREAD

**Issue by ly525** [ly525/blog#61]
## 源码实现
1. 按钮的状态变化: normal、hover、active、disabled

    - 因此在没有此四种状态的时候，按钮应该有一些基本的属性。
      - padding
      - font-size
      - border

    - 有状态的时候

      - color
      - background-color 亮度: normal < hover < click
      - border: color 与背景色保持一致

 2. theme-colors bg-color 产生预定义样式的按钮状态，包含：border、color
 3. 各种状态的color、bg-color、border
    - 背景色和文字颜色的函数关系, 比如：背景暗色、文字颜色应该是亮色

      ```scss
      // 相关讨论和链接
      // http://www.nbdtech.com/Blog/archive/2008/04/27/Calculating-the-Perceived-Brightness-of-a-Color.aspx
      // 参照 https://baike.baidu.com/item/YIQ/1977357?fr=aladdin
      @function color-yiq($color) {
        $r: red($color);
        $g: green($color);
        $b: blue($color); // $yiq 指颜色的明视度（Luminance），即亮度（Brightness）
        $yiq: (($r * 299) + ($g * 587) + ($b * 114)) / 1000; // 150
        @if ($yiq >=$yiq-contrasted-threshold) {
          // $yiq-text-dark: #212529 (gray-900);
          @return $yiq-text-dark;
        }
        @else {
          // white
          @return $yiq-text-light;
        }
      }
      ```

 4. 按钮大小

    1. TODO 疑惑🤔  这边的 Size 大中小，怎么定义`大`，怎么定义`小`呢?
    2. TODO 以目前来看，现在的`大`有些大，没有太多的场景需要使用到这么大的 button

        ```scss
        // button size 构成函数
        @mixin button-size($padding-y, $padding-x, $font-size, $line-height, $border-radius) {
          padding: $padding-y $padding-x;
          font-size: $font-size;
          line-height: $line-height;
          @if $enable-rounded {
              border-radius: $border-radius;
          }
          @else {
              border-radius: 0;
          }
        }
        ```

 5. loading 状态使用`css animation`实现， 而非 Icon

###  难点
- css 优先级，
css 优先级可视化工具：https://specificity.keegan.st/

    - `&:not(:disabled):not(.disabled)` 与 `&:not(:disabled)`
    ```css
    <!-- 33 行 -->
    .xx-btn:not(:disabled):not(.disabled) {
      cursor: pointer;
    }
    <!-- 37 行， 结果37行的被覆盖，说明下面的优先级更低 -->
    .xx-btn-primary.is-loading {
      cursor: default;
    }

    ```
